[tools]
"cargo:sheldon" = "latest"
deno = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
neovim = "latest"
node = "latest"
"npm:devcontainer" = "latest"
python = "3.11"
rust = "latest"
starship = "latest"
tmux = "latest"
